// PS2 pad button icons: see ps2_uiicons.h. PS2-333..337 (OPT11 NETUI).
#include "../doomdef.h"
#include "../g_input.h"
#include "../r_defs.h"
#include "../r_patch.h"
#include "../z_zone.h"

#include "ps2_menuhints.h" // cv_menuhints
#include "ps2_uiicons.h"

#include "ps2_uiicons_data.inc" // static const UINT8 uiicon_<name>[] and uiicons[]: generated by tools/ps2/ui_icons.py

_Static_assert(sizeof uiicons / sizeof uiicons[0] == PS2UI_NUMICONS, "ps2_uiicons_data.inc and ps2ui_icon_t disagree: run tools/ps2/ui_icons.py");

static patch_t *iconpatch[PS2UI_NUMICONS], *iconpatch_small[PS2UI_NUMICONS];
static boolean icontried[PS2UI_NUMICONS], icontried_small[PS2UI_NUMICONS];

boolean ps2ui_bigicons, ps2ui_hideicons;

// control character -> icon (the order of PS2I_* in ps2_uiicons.h)
static const SINT8 uitokenicon[0x16] =
{
	-1,
	PS2UI_CROSS, PS2UI_CIRCLE, PS2UI_SQUARE, PS2UI_TRIANGLE, PS2UI_L1, PS2UI_R1, PS2UI_L2, PS2UI_R2, // 0x01..0x08
	-1, -1,                                                                                         // \t \n
	PS2UI_START, PS2UI_SELECT,                                                                      // 0x0B 0x0C
	-1,                                                                                             // \r
	PS2UI_DPAD_UP, PS2UI_DPAD_DOWN, PS2UI_DPAD_LEFT, PS2UI_DPAD_RIGHT, PS2UI_L3, PS2UI_R3, PS2UI_DPAD_UD, PS2UI_DPAD_LR // 0x0E..0x15
};

INT32 PS2UI_TokenIcon(UINT8 c)
{
	return c < sizeof uitokenicon ? uitokenicon[c] : -1;
}

boolean PS2UI_SmallFor(INT32 capheight)
{
	return capheight < 13;
}

patch_t *PS2UI_PatchSized(INT32 icon, boolean small)
{
	if (icon < 0 || icon >= PS2UI_NUMICONS)
		return NULL;
	if (small && icon < (INT32)(sizeof uiicons_small / sizeof uiicons_small[0]) && uiicons_small[icon].data)
	{
		if (!iconpatch_small[icon] && !icontried_small[icon])
		{
			patch_t *p;

			icontried_small[icon] = true;
			p = Patch_TryCreateFromDoomPatch((softwarepatch_t *)uiicons_small[icon].data);
			if (p)
			{
				Z_ChangeTag(p, PU_STATIC);
				iconpatch_small[icon] = p;
			}
		}
		return iconpatch_small[icon];
	}
	if (!iconpatch[icon] && !icontried[icon])
	{
		// one zone block (structure, columns, posts, pixels) that no cache may drop and no level change frees: ~0.5 KB per icon, made when the icon is first drawn.
		// A failed attempt is not repeated every frame (no room: the icon is simply not drawn, the text around it is)
		patch_t *p;

		icontried[icon] = true;
		p = Patch_TryCreateFromDoomPatch((softwarepatch_t *)uiicons[icon].data);
		if (p)
		{
			Z_ChangeTag(p, PU_STATIC);
			iconpatch[icon] = p;
		}
	}
	return iconpatch[icon];
}

patch_t *PS2UI_Patch(INT32 icon)
{
	return PS2UI_PatchSized(icon, false);
}

INT32 PS2UI_TokenWidthSized(UINT8 c, boolean small)
{
	const INT32 icon = PS2UI_TokenIcon(c);

	if (icon < 0)
		return 0;
	if (small && icon < (INT32)(sizeof uiicons_small / sizeof uiicons_small[0]) && uiicons_small[icon].data)
		return (INT32)uiicons_small[icon].w + 1;
	return (INT32)uiicons[icon].w + 1;
}

INT32 PS2UI_TokenWidth(UINT8 c)
{
	return PS2UI_TokenWidthSized(c, false);
}

INT32 PS2UI_KeyIcon(INT32 k)
{
	static const SINT8 joy[12] = {PS2UI_CROSS, PS2UI_CIRCLE, PS2UI_SQUARE, PS2UI_TRIANGLE, PS2UI_L1, PS2UI_R1, PS2UI_SELECT, PS2UI_START, PS2UI_L3, PS2UI_R3, PS2UI_L2, PS2UI_R2};
	static const SINT8 hat[4] = {PS2UI_DPAD_UP, PS2UI_DPAD_DOWN, PS2UI_DPAD_LEFT, PS2UI_DPAD_RIGHT};

	// the layout of ps2_padmap.c: JOY1..JOY12 = Cross, Circle, Square, Triangle, L1, R1, Select, Start, L3, R3, L2, R2; hat 0 = up, down, left, right.
	// The second pad has the same buttons on KEY_2JOY1 / KEY_2HAT1.
	if (k >= KEY_JOY1 && k < KEY_JOY1 + 12)
		return joy[k - KEY_JOY1];
	if (k >= KEY_2JOY1 && k < KEY_2JOY1 + 12)
		return joy[k - KEY_2JOY1];
	if (k >= KEY_HAT1 && k < KEY_HAT1 + 4)
		return hat[k - KEY_HAT1];
	if (k >= KEY_2HAT1 && k < KEY_2HAT1 + 4)
		return hat[k - KEY_2HAT1];
	return -1;
}

const char *PS2UI_KeyToken(INT32 k)
{
	static const char *const tok[PS2UI_NUMICONS] = // text token of an icon that has one
	{
		[PS2UI_CROSS] = PS2I_CROSS, [PS2UI_CIRCLE] = PS2I_CIRCLE, [PS2UI_SQUARE] = PS2I_SQUARE, [PS2UI_TRIANGLE] = PS2I_TRIANGLE,
		[PS2UI_L1] = PS2I_L1, [PS2UI_R1] = PS2I_R1, [PS2UI_L2] = PS2I_L2, [PS2UI_R2] = PS2I_R2, [PS2UI_START] = PS2I_START, [PS2UI_SELECT] = PS2I_SELECT,
		[PS2UI_DPAD_UP] = PS2I_DPAD_UP, [PS2UI_DPAD_DOWN] = PS2I_DPAD_DOWN, [PS2UI_DPAD_LEFT] = PS2I_DPAD_LEFT, [PS2UI_DPAD_RIGHT] = PS2I_DPAD_RIGHT,
		[PS2UI_L3] = PS2I_L3, [PS2UI_R3] = PS2I_R3, [PS2UI_DPAD_UD] = PS2I_DPAD_UD, [PS2UI_DPAD_LR] = PS2I_DPAD_LR
	};
	const INT32 icon = PS2UI_KeyIcon(k);

	return icon >= 0 && tok[icon] ? tok[icon] : "";
}

// ---- the test card: console command "ps2_icons" (1 = on, 0 = off) draws every icon at its real size on two backgrounds, the hints of the screens in the normal and the thin
// font and a message box with the key names; for looking at the icons in both renderers (pictures of docs/GATES/g1/opt11-NETUI.md). Drawn by M_Drawer. ----
#include "../command.h"
#include "../console.h"
#include "../m_menu.h"
#include "../v_video.h"
#include "ps2_osk.h"

static INT32 card_on; // 1 the card, 2 only the on-screen keyboard

static void Command_Icons_f(void)
{
	card_on = COM_Argc() > 1 ? atoi(COM_Argv(1)) : !card_on;
	if (card_on == 2)
		PS2OSK_TestOpen(); // "ps2_icons 2": the on-screen keyboard instead of the message box
	else if (card_on)
		M_StartMessage("Press ENTER to continue\nor ESC to cancel.\n\n(Press a key)\n", NULL, MM_NOTHING);
}

void PS2UI_RegisterCommands(void)
{
	COM_AddCommand("ps2_icons", Command_Icons_f, 0);
}

void PS2UI_Card(void)
{
	INT32 i;

	if (card_on != 1)
		return;
	V_DrawFill(0, 0, 160, 84, 156); // two backgrounds, a dark and a light one; the middle band is left for the message box
	V_DrawFill(160, 0, 160, 84, 8);
	V_DrawFill(0, 126, 160, 74, 156);
	V_DrawFill(160, 126, 160, 74, 8);
	for (i = 0; i < PS2UI_NUMICONS; i++)
	{
		patch_t *p = PS2UI_Patch(i);
		const INT32 x = 6 + (i % 14) * 22, y = 4 + (i / 14) * 18;

		if (p)
			V_DrawScaledPatch(x, y, 0, p);
	}
	V_DrawString(6, 60, MENUCAPS, PS2I_CROSS " Enter  " PS2I_CIRCLE " Esc  " PS2I_SQUARE " Space  " PS2I_TRIANGLE " Tri");
	V_DrawString(6, 71, MENUCAPS, PS2I_L1 PS2I_R1 PS2I_L2 PS2I_R2 " shoulders  " PS2I_START PS2I_SELECT " start/select");
	V_DrawThinString(6, 130, V_ALLOWLOWERCASE, PS2I_CIRCLE " Cancel      " PS2I_DPAD_UD " Scroll list      " PS2I_CROSS " Download");
	V_DrawThinString(6, 146, V_ALLOWLOWERCASE, PS2I_CIRCLE " Back      " PS2I_SQUARE " Players      " PS2I_CROSS " Join");
	V_DrawCenteredString(160, 164, MENUCOLOR|MENUCAPS, va("%s Cancel", PS2I_CIRCLE));
	V_DrawRightAlignedString(314, 180, V_YELLOWMAP|MENUCAPS, va("%s or %s", PS2UI_KeyToken(KEY_JOY1), PS2UI_KeyToken(KEY_HAT1 + 3)));
	V_DrawString(6, 180, MENUCAPS, "Jump");
}

static boolean IsLetter(char c)
{
	return (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z');
}

// The text of a message box (M_StartMessage) for the console: the key names that a pad has no key for become icons (PS2-336).
// "ESC" -> Circle, "ENTER" -> Cross as whole words ("Press ESC", "Press ENTER to continue\nor ESC to cancel."), "Press a key" -> "Press <Cross> or <Circle>" (the buttons that close a box).
// A copy in a zone block (PU_STATIC), the caller frees it with Z_Free.
// One hint, one place (PS2-341): a message box says "(Press <Cross> or <Circle>)", "(Press 'Y' to confirm)", "Press <Circle>", "Press 'N' to ..." in its text, and the corner hints say
// <Cross> OK <Circle> Close / <Cross> Yes <Circle> No under it: with the corner hints on, those lines of the text (the lines that start with "Press" or "(Press" or are "(Y/N)", and
// the continuation of such a line that starts with a small letter) are not in the box. The text of the message itself stays.
static boolean IsHintLine(const char *line, size_t len)
{
	while (len && ((UINT8)*line >= 0x80 || *line == ' '))
	{
		line++;
		len--;
	}
	if (len >= 6 && !strncmp(line, "Press ", 6))
		return true;
	if (len >= 7 && !strncmp(line, "(Press ", 7))
		return true;
	return len == 5 && !strncmp(line, "(Y/N)", 5);
}

static void StripHintLines(char *text)
{
	const size_t len = strlen(text);
	char *tmp = Z_Malloc(len + 2, PU_STATIC, NULL), *o = tmp;
	const char *p = text;
	boolean prevcut = false, any = false;

	while (*p)
	{
		const char *e = strchr(p, '\n');
		const size_t ll = e ? (size_t)(e - p) : strlen(p);
		boolean cut = IsHintLine(p, ll) || (prevcut && ll && p[0] >= 'a' && p[0] <= 'z');

		if (!cut)
		{
			memcpy(o, p, ll);
			o += ll;
			*o++ = '\n';
			if (ll)
				any = true;
		}
		prevcut = cut;
		p += ll + (e ? 1 : 0);
	}
	while (o > tmp && o[-1] == '\n' && (o - tmp < 2 || o[-2] == '\n')) // one newline at the end, as the messages have
		o--;
	*o = '\0';
	if (any && o != tmp)
		memcpy(text, tmp, (size_t)(o - tmp) + 1);
	Z_Free(tmp);
}

char *PS2UI_Message(const char *src)
{
	static const struct { const char *word; const char *with; } words[] = {{"ESC", PS2I_CIRCLE}, {"ENTER", PS2I_CROSS}};
	const size_t len = strlen(src);
	char *out = Z_Malloc(len * 2 + 32, PU_STATIC, NULL), *o = out;
	const char *s = src;

	while (*s)
	{
		size_t i;
		boolean done = false;

		if (!strncmp(s, "Press a key", 11))
		{
			// the keys that close a message box are Enter, Escape, Space, N, Y and Delete: of the pad's buttons Cross and Circle (and Triangle = N)
			memcpy(o, "Press " PS2I_CROSS " or " PS2I_CIRCLE, 6 + 1 + 4 + 1);
			o += 6 + 1 + 4 + 1;
			s += 11;
			continue;
		}
		for (i = 0; i < sizeof words / sizeof words[0] && !done; i++)
		{
			const size_t wl = strlen(words[i].word);

			if (!strncmp(s, words[i].word, wl) && !(s > src && IsLetter(s[-1])) && !IsLetter(s[wl]))
			{
				*o++ = words[i].with[0];
				s += wl;
				done = true;
			}
		}
		if (!done)
			*o++ = *s++;
	}
	*o = '\0';
	if (cv_menuhints.value)
		StripHintLines(out);
	return out;
}
