// PS2 pad button icons: see ps2_uiicons.h. PS2-333..337 (OPT11 NETUI).
#include "../doomdef.h"
#include "../g_input.h"
#include "../r_defs.h"
#include "../r_patch.h"
#include "../z_zone.h"

#include "ps2_uiicons.h"

#include "ps2_uiicons_data.inc" // static const UINT8 uiicon_<name>[] and uiicons[]: generated by tools/ps2/ui_icons.py

_Static_assert(sizeof uiicons / sizeof uiicons[0] == PS2UI_NUMICONS, "ps2_uiicons_data.inc and ps2ui_icon_t disagree: run tools/ps2/ui_icons.py");

static patch_t *iconpatch[PS2UI_NUMICONS];
static boolean icontried[PS2UI_NUMICONS];

// control character -> icon (the order of PS2I_* in ps2_uiicons.h)
static const SINT8 tokenicon[0x16] =
{
	-1,
	PS2UI_CROSS, PS2UI_CIRCLE, PS2UI_SQUARE, PS2UI_TRIANGLE, PS2UI_L1, PS2UI_R1, PS2UI_L2, PS2UI_R2, // 0x01..0x08
	-1, -1,                                                                                         // \t \n
	PS2UI_START, PS2UI_SELECT,                                                                      // 0x0B 0x0C
	-1,                                                                                             // \r
	PS2UI_DPAD_UP, PS2UI_DPAD_DOWN, PS2UI_DPAD_LEFT, PS2UI_DPAD_RIGHT, PS2UI_L3, PS2UI_R3, PS2UI_LSTICK, PS2UI_RSTICK // 0x0E..0x15
};

INT32 PS2UI_TokenIcon(UINT8 c)
{
	return c < sizeof tokenicon ? tokenicon[c] : -1;
}

patch_t *PS2UI_Patch(INT32 icon)
{
	if (icon < 0 || icon >= PS2UI_NUMICONS)
		return NULL;
	if (!iconpatch[icon] && !icontried[icon])
	{
		// one zone block (structure, columns, posts, pixels) that no cache may drop and no level change frees: ~0.5 KB per icon, made when the icon is first drawn.
		// A failed attempt is not repeated every frame (no room: the icon is simply not drawn, the text around it is)
		patch_t *p;

		icontried[icon] = true;
		p = Patch_TryCreateFromDoomPatch((softwarepatch_t *)uiicons[icon].data);
		if (p)
		{
			Z_ChangeTag(p, PU_STATIC);
			iconpatch[icon] = p;
		}
	}
	return iconpatch[icon];
}

INT32 PS2UI_TokenWidth(UINT8 c)
{
	const INT32 icon = PS2UI_TokenIcon(c);

	return icon < 0 ? 0 : (INT32)uiicons[icon].w + 1;
}

INT32 PS2UI_KeyIcon(INT32 k)
{
	static const SINT8 joy[12] = {PS2UI_CROSS, PS2UI_CIRCLE, PS2UI_SQUARE, PS2UI_TRIANGLE, PS2UI_L1, PS2UI_R1, PS2UI_SELECT, PS2UI_START, PS2UI_L3, PS2UI_R3, PS2UI_L2, PS2UI_R2};
	static const SINT8 hat[4] = {PS2UI_DPAD_UP, PS2UI_DPAD_DOWN, PS2UI_DPAD_LEFT, PS2UI_DPAD_RIGHT};

	// the layout of ps2_padmap.c: JOY1..JOY12 = Cross, Circle, Square, Triangle, L1, R1, Select, Start, L3, R3, L2, R2; hat 0 = up, down, left, right.
	// The second pad has the same buttons on KEY_2JOY1 / KEY_2HAT1.
	if (k >= KEY_JOY1 && k < KEY_JOY1 + 12)
		return joy[k - KEY_JOY1];
	if (k >= KEY_2JOY1 && k < KEY_2JOY1 + 12)
		return joy[k - KEY_2JOY1];
	if (k >= KEY_HAT1 && k < KEY_HAT1 + 4)
		return hat[k - KEY_HAT1];
	if (k >= KEY_2HAT1 && k < KEY_2HAT1 + 4)
		return hat[k - KEY_2HAT1];
	return -1;
}

const char *PS2UI_KeyToken(INT32 k)
{
	static const char *const tok[PS2UI_NUMICONS] = // text token of an icon that has one
	{
		[PS2UI_CROSS] = PS2I_CROSS, [PS2UI_CIRCLE] = PS2I_CIRCLE, [PS2UI_SQUARE] = PS2I_SQUARE, [PS2UI_TRIANGLE] = PS2I_TRIANGLE,
		[PS2UI_L1] = PS2I_L1, [PS2UI_R1] = PS2I_R1, [PS2UI_L2] = PS2I_L2, [PS2UI_R2] = PS2I_R2, [PS2UI_START] = PS2I_START, [PS2UI_SELECT] = PS2I_SELECT,
		[PS2UI_DPAD_UP] = PS2I_DPAD_UP, [PS2UI_DPAD_DOWN] = PS2I_DPAD_DOWN, [PS2UI_DPAD_LEFT] = PS2I_DPAD_LEFT, [PS2UI_DPAD_RIGHT] = PS2I_DPAD_RIGHT,
		[PS2UI_L3] = PS2I_L3, [PS2UI_R3] = PS2I_R3
	};
	const INT32 icon = PS2UI_KeyIcon(k);

	return icon >= 0 && tok[icon] ? tok[icon] : "";
}
