/* Drawer equivalence + COP0 cycle bench. One translation unit: the stub environment, the drawer sources
 * (src/r_draw8.c, src/r_draw8_npo2.c from -I order: HEAD snapshot for the reference build, working tree for the candidate)
 * and the driver. Built by tools/ps2/rdraw_bench.py for the host (MSVC, hashes only) and the EE (PCSX2, hashes + cycles).
 *
 * Output (one line per drawer/scenario):  RB <drawer> <scenario> calls=<n> cyc=<cycles per call*10> hash=<fnv64 of the frame after the run>
 * The hash covers the whole 320x200 framebuffer after the first repetition, so any differing pixel changes it.
 */
#include "rdraw_stub.h"

#if defined(_MSC_VER)
#pragma warning(push)
#pragma warning(disable: 4244 4267 4018 4146 4305 4204 4100 4101 4189)
#endif
#ifdef RDRAW_BROKEN /* negative control: shifts by one bit less everywhere (column drawers) and a wrong x shift in the span setup */
#undef FRACBITS
#define FRACBITS 15
#endif
#include "lighting.inc" /* tiltlighting + R_CalcSlopeLight of src/r_draw.c (generated by rdraw_bench.py) */
#include "r_draw8.c"
#include "r_draw8_npo2.c"
#if defined(_MSC_VER)
#pragma warning(pop)
#endif

#ifdef _EE
static inline unsigned cyc_count(void) { unsigned v; __asm__ volatile("mfc0 %0,$9" : "=r"(v)); return v; }
#else
static inline unsigned cyc_count(void) { return 0; }
#endif

static UINT32 rng_state = 0x1234567u;
static UINT32 rnd(void) { rng_state ^= rng_state << 13; rng_state ^= rng_state >> 17; rng_state ^= rng_state << 5; return rng_state; }
static INT32 rnd_range(INT32 lo, INT32 hi) { return lo + (INT32)(rnd() % (UINT32)(hi - lo + 1)); }

#define FB_SIZE (320 * 200)
#ifdef RDRAW_STRESS
#define NCALLS 1024
#else
#define NCALLS 48
#endif
static UINT8 *fb, *fb_bg, *fb_pattern, *cmaps, *transtab, *transl, *flat8;
static UINT16 *sprite16;
static UINT8 *column_src;

static UINT64 fnv(UINT64 h, const UINT8 *p, size_t n)
{
	size_t i;
	for (i = 0; i + 4 <= n; i += 4)
	{
		UINT32 w;
		memcpy(&w, p + i, 4);
		h = (h ^ w) * 1099511628211ull;
		h ^= h >> 29;
	}
	return h;
}

typedef enum { K_COL, K_SPAN, K_SPAN16, K_WATER, K_FOGSPAN, K_FOGCOL, K_SOLID, K_SHADE, K_DROP } kind_t;
typedef struct { const char *name; void (*fn)(void); kind_t kind; int npo2; } entry_t;

static void nop(void) {}

static const entry_t entries[] = {
	{"R_DrawColumn_8", R_DrawColumn_8, K_COL, 0},
	{"R_DrawColumnClamped_8", R_DrawColumnClamped_8, K_COL, 0},
	{"R_Draw2sMultiPatchColumn_8", R_Draw2sMultiPatchColumn_8, K_COL, 0},
	{"R_Draw2sMultiPatchTranslucentColumn_8", R_Draw2sMultiPatchTranslucentColumn_8, K_COL, 0},
	{"R_DrawShadeColumn_8", R_DrawShadeColumn_8, K_SHADE, 0},
	{"R_DrawTranslucentColumn_8", R_DrawTranslucentColumn_8, K_COL, 0},
	{"R_DrawTranslucentColumnClamped_8", R_DrawTranslucentColumnClamped_8, K_COL, 0},
	{"R_DrawDropShadowColumn_8", R_DrawDropShadowColumn_8, K_DROP, 0},
	{"R_DrawTranslatedTranslucentColumn_8", R_DrawTranslatedTranslucentColumn_8, K_COL, 0},
	{"R_DrawTranslatedColumn_8", R_DrawTranslatedColumn_8, K_SHADE, 0},
	{"R_DrawFogColumn_8", R_DrawFogColumn_8, K_FOGCOL, 0},
	{"R_DrawSpan_8", R_DrawSpan_8, K_SPAN, 0},
	{"R_DrawTranslucentSpan_8", R_DrawTranslucentSpan_8, K_SPAN, 0},
	{"R_DrawWaterSpan_8", R_DrawWaterSpan_8, K_WATER, 0},
	{"R_DrawSplat_8", R_DrawSplat_8, K_SPAN, 0},
	{"R_DrawTranslucentSplat_8", R_DrawTranslucentSplat_8, K_SPAN, 0},
	{"R_DrawFloorSprite_8", R_DrawFloorSprite_8, K_SPAN16, 0},
	{"R_DrawTranslucentFloorSprite_8", R_DrawTranslucentFloorSprite_8, K_SPAN16, 0},
	{"R_DrawFogSpan_8", R_DrawFogSpan_8, K_FOGSPAN, 0},
	{"R_DrawSolidColorSpan_8", R_DrawSolidColorSpan_8, K_SOLID, 0},
	{"R_DrawTransSolidColorSpan_8", R_DrawTransSolidColorSpan_8, K_SOLID, 0},
	{"R_DrawWaterSolidColorSpan_8", R_DrawWaterSolidColorSpan_8, K_SOLID, 0},
	{"R_DrawSpan_NPO2_8", R_DrawSpan_NPO2_8, K_SPAN, 1},
	{"R_DrawTranslucentSpan_NPO2_8", R_DrawTranslucentSpan_NPO2_8, K_SPAN, 1},
	{"R_DrawWaterSpan_NPO2_8", R_DrawWaterSpan_NPO2_8, K_WATER, 1},
	{"R_DrawSplat_NPO2_8", R_DrawSplat_NPO2_8, K_SPAN, 1},
	{"R_DrawTranslucentSplat_NPO2_8", R_DrawTranslucentSplat_NPO2_8, K_SPAN, 1},
	{"R_DrawFloorSprite_NPO2_8", R_DrawFloorSprite_NPO2_8, K_SPAN16, 1},
	{"R_DrawTranslucentFloorSprite_NPO2_8", R_DrawTranslucentFloorSprite_NPO2_8, K_SPAN16, 1},
};
#define NENT ((int)(sizeof entries / sizeof entries[0]))

/* column scenarios: texture height (0 = sprite post), pixel count range, fracstep (iscale) */
typedef struct { const char *name; INT32 texh; INT32 cmin, cmax; fixed_t iscale; } colsc_t;
static const colsc_t colsc[] = {
	{"po2-h128-n100-1.0", 128, 90, 110, 0x10000},
	{"po2-h64-n100-0.5", 64, 90, 110, 0x8000},
	{"po2-h128-n8-1.0", 128, 6, 10, 0x10000},
	{"po2-h256-n190-1.5", 256, 180, 199, 0x18000},
	{"npo2-h72-n100-1.0", 72, 90, 110, 0x10000},
	{"npo2-h100-n150-0.7", 100, 140, 160, 0xB000},
	{"npo2-h24-n30-0.4", 24, 25, 35, 0x6666},
	{"post-n40-1.3", 0, 36, 44, 0x14000},
	{"post-n12-0.8", 0, 10, 14, 0xCCCC},
};
#define NCOLSC ((int)(sizeof colsc / sizeof colsc[0]))

/* span scenarios: flat bits (6 = 64x64, 7 = 128x128, 8 = 256x256, 0 = npo2 63x47), count range, step magnitude */
typedef struct { const char *name; int bits; INT32 cmin, cmax; fixed_t smax; } spansc_t;
static const spansc_t spansc[] = {
	{"f64-n100-s1.0", 6, 90, 110, 0x10000},
	{"f64-n320-s0.3", 6, 316, 320, 0x4000},
	{"f64-n16-s1.5", 6, 14, 18, 0x18000},
	{"f64-n5-s1.0", 6, 3, 7, 0x10000},
	{"f128-n100-s1.0", 7, 90, 110, 0x10000},
	{"f256-n60-s0.9", 8, 50, 70, 0xE000},
#ifdef RDRAW_STRESS
	{"edge-n1", 6, 1, 1, 0x10000},
	{"edge-n2-3", 6, 2, 3, 0x10000},
	{"edge-n7-8", 6, 7, 8, 0x10000},
	{"edge-n15-16", 6, 15, 16, 0x10000},
	{"edge-n31-33", 6, 31, 33, 0x10000},
	{"npo2-wrap-many", 6, 35, 319, 0x1C00000},
#endif
};
#define NSPANSC ((int)(sizeof spansc / sizeof spansc[0]))

static void set_flat(int bits, int npo2)
{
	if (npo2)
	{
		ds_flatwidth = 63;
		ds_flatheight = 47;
		nflatshiftup = 10; nflatxshift = 26; nflatyshift = 20; nflatmask = 4032; /* unused by NPO2 drawers */
	}
	else
	{
		const UINT32 size = 1u << bits;
		ds_flatwidth = ds_flatheight = (UINT16)size;
		nflatshiftup = 16 - bits;
		nflatxshift = 16 + nflatshiftup;
#ifdef RDRAW_BROKEN
		nflatxshift++;
#endif
		nflatyshift = nflatxshift - bits;
		nflatmask = (size - 1) * size;
	}
}

static void fill_fb(UINT8 *p) { memcpy(p, fb_pattern, FB_SIZE); }

static void run_entry(const entry_t *e)
{
	UINT64 hash = 1469598103934665603ull;
	int sc, nsc = (e->kind <= K_COL || e->kind == K_SHADE || e->kind == K_DROP || e->kind == K_FOGCOL) ? NCOLSC : NSPANSC;
	for (sc = 0; sc < nsc; sc++)
	{
		struct { INT32 x, yl, yh; fixed_t texmid; fixed_t iscale; INT32 xs1, xs2, y; fixed_t xf, yf, xst, yst; INT32 bgofs, wofs, cmap, tmap, texh, post; } P[NCALLS];
		unsigned best = 0xFFFFFFFFu, bestovh = 0xFFFFFFFFu;
		int rep, i;
		const char *scname;
		int is_col = (e->kind == K_COL || e->kind == K_SHADE || e->kind == K_DROP || e->kind == K_FOGCOL);

		rng_state = 0x9E3779B9u ^ (UINT32)(sc * 7919 + 17);
		scname = is_col ? colsc[sc].name : spansc[sc].name;
		for (i = 0; i < NCALLS; i++)
		{
			P[i].cmap = rnd_range(0, 31) * 256;
			P[i].tmap = rnd_range(0, 9);
			if (is_col)
			{
				const colsc_t *c = &colsc[sc];
				INT32 n = rnd_range(c->cmin, c->cmax);
				fixed_t frac0;
				P[i].x = rnd_range(0, 319);
				P[i].yl = rnd_range(0, 200 - n);
				P[i].yh = P[i].yl + n - 1;
				P[i].iscale = c->iscale + rnd_range(-0x100, 0x100);
				P[i].texh = c->texh;
				P[i].post = c->texh ? c->texh : 256;
				if (c->texh)
				{
					frac0 = (fixed_t)(rnd() % (UINT32)(c->texh << 16));
					switch (e->kind == K_SHADE ? 0 : (rnd() & 3)) /* in range, a few times below zero or beyond the end (the masking/normalising drawers); unmasked drawers stay inside */
					{
						case 1: frac0 -= c->texh << 16; break;
						case 2: frac0 += 3 * (c->texh << 16); break;
						default: break;
					}
				}
				else
					frac0 = (fixed_t)(rnd() % (8u << 16)); /* a sprite post is indexed directly: stay inside it */
				P[i].texmid = frac0 - FixedMul((P[i].yl << FRACBITS) - centeryfrac, P[i].iscale);
			}
			else
			{
				const spansc_t *s = &spansc[sc];
				INT32 n = rnd_range(s->cmin, s->cmax);
				P[i].xs1 = rnd_range(0, 320 - n);
				P[i].xs2 = P[i].xs1 + n - 1;
				P[i].y = rnd_range(3, 196);
				P[i].bgofs = rnd_range(-2, 2);
				P[i].wofs = rnd_range(0, 16384);
				P[i].xst = rnd_range(-s->smax, s->smax);
				P[i].yst = rnd_range(-s->smax, s->smax);
				if (e->npo2)
				{
					P[i].xf = (fixed_t)(rnd() % (63u << 16));
					P[i].yf = (fixed_t)(rnd() % (47u << 16));
#ifdef RDRAW_STRESS
					// Include negative starts, exact periods, zero and boundary steps;
					// exercise both the bounded path and original multi-wrap fallback.
					switch (i & 7)
					{
					case 0: P[i].xf = (fixed_t)rnd(); P[i].yf = (fixed_t)rnd(); break;
					case 1: P[i].xf = -(63 << 16); P[i].yf = -(47 << 16); break;
					case 2: P[i].xf = (63 << 16); P[i].yf = (47 << 16); break;
					case 3: P[i].xst = 0; P[i].yst = 0; break;
					case 4: P[i].xst = (63 << 16) - 1; P[i].yst = -(47 << 16) + 1; break;
					case 5: P[i].xst = -(63 << 16); P[i].yst = (47 << 16); break;
					case 6: P[i].xf = -1; P[i].yf = -1; break;
					default: break;
					}
#endif
				}
				else
				{
					P[i].xf = (fixed_t)rnd();
					P[i].yf = (fixed_t)rnd();
				}
			}
		}
		if (!is_col)
			set_flat(e->npo2 ? 0 : spansc[sc].bits, e->npo2);
		for (rep = 0; rep < 3; rep++)
		{
			unsigned t0, dt;
			int pass;
			for (pass = 0; pass < 2; pass++) /* pass 0: overhead (nop), pass 1: drawer */
			{
				void (*fn)(void) = pass ? e->fn : nop;
				fill_fb(fb);
				memcpy(fb_bg, fb_pattern + 17, FB_SIZE - 17);
				t0 = cyc_count();
				for (i = 0; i < NCALLS; i++)
				{
					if (is_col)
					{
						dc_x = P[i].x; dc_yl = P[i].yl; dc_yh = P[i].yh; dc_iscale = P[i].iscale; dc_texturemid = P[i].texmid;
						dc_texheight = P[i].texh; dc_postlength = P[i].post;
						dc_colormap = cmaps + P[i].cmap; dc_source = column_src; dc_transmap = transtab + P[i].tmap * 65536;
						dc_translation = transl;
					}
					else
					{
						ds_y = P[i].y; ds_x1 = P[i].xs1; ds_x2 = P[i].xs2; ds_xfrac = P[i].xf; ds_yfrac = P[i].yf;
						ds_xstep = P[i].xst; ds_ystep = P[i].yst; ds_bgofs = P[i].bgofs; ds_waterofs = P[i].wofs;
						ds_colormap = cmaps + P[i].cmap; ds_transmap = transtab + P[i].tmap * 65536; ds_translation = transl;
						ds_source = (e->kind == K_SPAN16) ? (UINT8 *)sprite16 : flat8;
					}
					fn();
#ifdef RDRAW_STRESS
					// Hash each call before another draw can overwrite a wrong pixel.
					// The whole target row (or every row of the target column) is covered.
					if (pass && rep == 0)
					{
						if (is_col)
						{
							int row;
							const int x = P[i].x > 316 ? 316 : P[i].x;
							for (row = 0; row < 200; row++) hash = fnv(hash, fb + row * 320 + x, 4);
						}
						else hash = fnv(hash, fb + P[i].y * 320, 320);
					}
#endif
				}
				dt = cyc_count() - t0;
				if (pass == 0)
				{
					if (dt < bestovh) bestovh = dt;
				}
				else if (dt < best)
					best = dt;
				if (pass && rep == 0)
					hash = fnv(hash, fb, FB_SIZE);
			}
		}
		printf("RB %s %s calls=%d cyc=%u hash=%016llx\n", e->name, scname, NCALLS,
			(unsigned)(((best > bestovh ? best - bestovh : 0) * 10u) / NCALLS), (unsigned long long)hash);
	}
}

int main(int argc, char **argv)
{
	int i, only = -1;
	(void)argc; (void)argv;
	fb = (UINT8 *)malloc(FB_SIZE + 64);
	fb_bg = (UINT8 *)malloc(FB_SIZE + 64);
	fb_pattern = (UINT8 *)malloc(FB_SIZE + 64);
	cmaps = (UINT8 *)malloc(65536 * 2);
	transtab = (UINT8 *)malloc(65536 * 10);
	transl = (UINT8 *)malloc(256);
	flat8 = (UINT8 *)malloc(2048 * 2048 / 16 + 64);
	sprite16 = (UINT16 *)malloc(65536 * 2);
	column_src = (UINT8 *)malloc(4096);
	if (!fb || !fb_bg || !fb_pattern || !cmaps || !transtab || !transl || !flat8 || !sprite16 || !column_src)
		return 2;
	/* the 8-byte-aligned blocks come from malloc; make the framebuffer 64-byte aligned like the engine's */
	fb = (UINT8 *)(((size_t)fb + 63) & ~(size_t)63);
	fb_bg = (UINT8 *)(((size_t)fb_bg + 63) & ~(size_t)63);
	rng_state = 0xC0FFEEu;
	for (i = 0; i < FB_SIZE; i++) fb_pattern[i] = (UINT8)(rnd() >> 24);
	for (i = 0; i < 65536 * 2; i++) cmaps[i] = (UINT8)(rnd() >> 24);
	for (i = 0; i < 65536 * 10; i++) transtab[i] = (UINT8)(rnd() >> 24);
	for (i = 0; i < 256; i++) transl[i] = (UINT8)(rnd() >> 24);
	for (i = 0; i < 2048 * 2048 / 16; i++) flat8[i] = (UINT8)(rnd() >> 24);
	for (i = 0; i < 65536; i++) sprite16[i] = (UINT16)(rnd() >> 16);
	for (i = 0; i < 4096; i++) column_src[i] = (UINT8)(rnd() >> 24);
	/* sprites/splats: some transparent pixels */
	for (i = 0; i < 2048 * 2048 / 16; i += 5) flat8[i] = TRANSPARENTPIXEL;
	for (i = 0; i < 65536; i += 5) sprite16[i] &= 0x00FF;
	screens[0] = fb; screens[1] = fb_bg;
	topleft = fb;
	colormaps = cmaps;
	colfuncs[0] = R_DrawColumn_8;
	for (i = 0; i < MAXLIGHTSCALE; i++) planezlight[i] = cmaps + (i % 32) * 256;
	if (argc > 1) only = atoi(argv[1]);
	printf("RB START entries=%d\n", NENT);
	for (i = 0; i < NENT; i++)
		if (only < 0 || only == i)
			run_entry(&entries[i]);
	printf("RB DONE\n");
	return 0;
}
