"""Generates lt_fields.lua: for every Lua-visible structure (sector, line, side, vertex, seg, subsector, node, slope, polyobj, mobj, player, skin, mapheader, mobjinfo, sfxinfo, extracolormap)
the list of its fields, read from the *_opt[] tables of src/lua_*.c, and a Lua script that reads every field of the first objects and prints it ("LQ field ..."), so that the PC
and the PS2 build can be compared field by field. usage: python3 tools/ps2/luatests/gen_fields.py > tools/ps2/luatests/lt_fields.lua"""
import re
import sys
from pathlib import Path

SRC = Path(__file__).resolve().parents[3] / 'src'


def opts(path, name):
    t = (SRC / path).read_text()
    m = re.search(r'(?:static )?const char \*const %s\[\] ?= ?\{(.*?)NULL' % name, t, re.S)
    if not m:
        raise SystemExit(f'{path}: {name} not found')
    return re.findall(r'"([^"]+)"', m.group(1))


STRUCTS = {
    'sector': ('lua_maplib.c', 'sector_opt'), 'subsector': ('lua_maplib.c', 'subsector_opt'), 'line': ('lua_maplib.c', 'line_opt'), 'side': ('lua_maplib.c', 'side_opt'),
    'vertex': ('lua_maplib.c', 'vertex_opt'), 'ffloor': ('lua_maplib.c', 'ffloor_opt'), 'seg': ('lua_maplib.c', 'seg_opt'), 'node': ('lua_maplib.c', 'node_opt'),
    'slope': ('lua_maplib.c', 'slope_opt'), 'mapheader': ('lua_maplib.c', 'mapheaderinfo_opt'), 'mobj': ('lua_mobjlib.c', 'mobj_opt'), 'mapthing': ('lua_mobjlib.c', 'mapthing_opt'),
    'player': ('lua_playerlib.c', 'player_opt'), 'ticcmd': ('lua_playerlib.c', 'ticcmd_opt'), 'skin': ('lua_skinlib.c', 'skin_opt'), 'polyobj': ('lua_polyobjlib.c', 'polyobj_opt'),
    'mobjinfo': ('lua_infolib.c', 'mobjinfo_opt'), 'sfxinfo': ('lua_infolib.c', 'sfxinfo_ropt'), 'extracolormap': ('lua_colorlib.c', 'extracolormap_opt'),
}
print('-- GENERATED by gen_fields.py from the *_opt[] tables of src/lua_*.c: do not edit')
print('local F = {}')
SKIP = {'mapheader': {'interscreen', 'runsoc', 'scriptname'}}   # char[] fields that hold "#" followed by uninitialised bytes in the PC build (upstream)
for k, (f, n) in STRUCTS.items():
    print('F.%s = {%s}' % (k, ','.join('"%s"' % x for x in opts(f, n) if x not in SKIP.get(k, ()))))
print(r'''
local function P(...)
	local t = {...}
	local s = {}
	for i = 1, select("#", ...) do s[#s+1] = tostring(t[i]) end
	print("LQ " .. table.concat(s, " "))
end
-- indexes of the engine structures, so that a reference to a sector / line / side / vertex prints as its number (pointers differ)
local idx = {sector = {}, line = {}, side = {}, vertex = {}, subsector = {}, seg = {}, node = {}}
local HAVE_SEGS = pcall(function() return segs[0] end)
local function build()
	for i = 0, #sectors - 1 do idx.sector[sectors[i]] = i end
	for i = 0, #lines - 1 do idx.line[lines[i]] = i end
	for i = 0, #sides - 1 do idx.side[sides[i]] = i end
	for i = 0, #vertexes - 1 do idx.vertex[vertexes[i]] = i end
	for i = 0, #subsectors - 1 do idx.subsector[subsectors[i]] = i end
	if HAVE_SEGS then
		for i = 0, #segs - 1 do idx.seg[segs[i]] = i end
		for i = 0, #nodes - 1 do idx.node[nodes[i]] = i end
	end
end
local function fmt(v, depth)
	local t = type(v)
	if t == "number" or t == "boolean" or t == "nil" then return tostring(v) end
	if t == "string" then return '"' .. v .. '"' end
	if t == "userdata" then
		for _, kind in ipairs({"sector", "line", "side", "vertex", "subsector", "seg", "node"}) do
			local i = idx[kind][v]
			if i then return kind .. "#" .. i end
		end
		if depth and depth > 0 then
			local ok, ty = pcall(function() return v.type end)
			local ok2, x = pcall(function() return v.x end)
			if ok and ok2 and type(ty) == "number" and type(x) == "number" then return "mo(" .. ty .. "," .. (x >> 16) .. ")" end
		end
		return "userdata"
	end
	if t == "table" then
		local keys = {}
		for k in pairs(v) do keys[#keys+1] = tostring(k) end
		table.sort(keys)
		return "table[" .. #keys .. "]"
	end
	return t
end
local function dump(kind, obj, tag)
	local out = {}
	for _, f in ipairs(F[kind]) do
		local ok, v = pcall(function() return obj[f] end)
		if ok then out[#out+1] = f .. "=" .. fmt(v, 1) else out[#out+1] = f .. "=E:" .. (tostring(v):gsub("^.-:%d+: ", "")) end
	end
	P(kind, tag, table.concat(out, " "))
end
local function digest(kind, list, n)
	local h = 17
	for i = 0, n - 1 do
		local obj = list(i)
		if obj then
			for _, f in ipairs(F[kind]) do
				local ok, v = pcall(function() return obj[f] end)
				local s = ok and fmt(v) or "E"
				for c = 1, #s do h = (h * 31 + s:byte(c)) % 1000003 end
			end
		end
	end
	return h
end
local done = false
addHook("ThinkFrame", function()
	if done or leveltime ~= 20 then return end
	done = true
	build()
	P("counts", #sectors, #lines, #sides, #vertexes, #subsectors, HAVE_SEGS)
	P("digest_all", "sector", digest("sector", function(i) return sectors[i] end, #sectors), "line", digest("line", function(i) return lines[i] end, #lines),
		"side", digest("side", function(i) return sides[i] end, #sides), "vertex", digest("vertex", function(i) return vertexes[i] end, #vertexes),
		"subsector", digest("subsector", function(i) return subsectors[i] end, #subsectors))
	if HAVE_SEGS then P("digest_segs", digest("seg", function(i) return segs[i] end, #segs), digest("node", function(i) return nodes[i] end, #nodes)) end
	for i = 0, min(#sectors, 40) - 1 do dump("sector", sectors[i], i) end
	for i = 0, min(#lines, 60) - 1 do dump("line", lines[i], i) end
	for i = 0, min(#sides, 60) - 1 do dump("side", sides[i], i) end
	for i = 0, min(#vertexes, 30) - 1 do dump("vertex", vertexes[i], i) end
	for i = 0, min(#subsectors, 30) - 1 do dump("subsector", subsectors[i], i) end
	if HAVE_SEGS then
		for i = 0, min(#segs, 40) - 1 do dump("seg", segs[i], i) end
		for i = 0, min(#nodes, 30) - 1 do dump("node", nodes[i], i) end
	end
	local function try(sec, f) local ok, e = pcall(f) if not ok then P("section_err", sec, (tostring(e):gsub("^.-:%d+: ", ""))) end end
	try("slopes", function() local n = 0 for sl in slopes.iterate do n = n + 1 if n <= 5 then dump("slope", sl, n) end end P("slopes", n) end)
	try("polyobjs", function() local n = 0 for po in polyobjects.iterate do n = n + 1 if n <= 3 then dump("polyobj", po, n) end end P("polyobjs", n) end)
	local k = 0
	for mo in mobjs.iterate() do
		k = k + 1
		if k <= 120 then dump("mobj", mo, k) end
	end
	P("mobjcount", k)
	for i = 0, 3 do if players[i] then dump("player", players[i], i) if players[i].cmd then dump("ticcmd", players[i].cmd, i) end end end
	for i = 0, 7 do local ok, sk = pcall(function() return skins[i] end) if ok and sk then dump("skin", sk, i) end end
	local ok, mh = pcall(function() return mapheaderinfo[gamemap] end) if ok and mh then dump("mapheader", mh, gamemap) end
	for _, t in ipairs({MT_PLAYER, MT_BLUECRAWLA, MT_RING, MT_THOK, MT_YELLOWSPRING, MT_GFZFLOWER1}) do dump("mobjinfo", mobjinfo[t], t) end
	for _, t in ipairs({sfx_jump, sfx_thok, sfx_pop}) do dump("sfxinfo", sfxinfo[t], t) end
	for i = 0, min(#sectors, 40) - 1 do
		local s = sectors[i]
		local ok, ex = pcall(function() return s.extra_colormap end)
		if ok and ex then dump("extracolormap", ex, i) end
		local ok2, ff = pcall(function() return s.ffloors end)
		if ok2 and ff then local c = 0 for f in ff() do c = c + 1 if c <= 3 then dump("ffloor", f, i .. "/" .. c) end end if c > 0 then P("ffloors", i, c) end end
	end
	try("mapthings", function() local mt = 0 for i = 0, #mapthings - 1 do mt = mt + 1 if i < 40 then dump("mapthing", mapthings[i], i) end end P("mapthings", mt) end)
	P("DONE_FIELDS")
end)
''')
