-- GENERATED by gen_fields.py from the *_opt[] tables of src/lua_*.c: do not edit
local F = {}
F.sector = {"valid","floorheight","ceilingheight","floorpic","floorxoffset","flooryoffset","floorxscale","flooryscale","floorangle","ceilingpic","ceilingxoffset","ceilingyoffset","ceilingxscale","ceilingyscale","ceilingangle","lightlevel","floorlightlevel","floorlightabsolute","floorlightsec","ceilinglightlevel","ceilinglightabsolute","ceilinglightsec","special","tag","taglist","thinglist","heightsec","camsec","lines","ffloors","f_slope","c_slope","colormap","flags","specialflags","damagetype","triggertag","triggerer","friction","gravity"}
F.subsector = {"valid","sector","numlines","firstline","polyList"}
F.line = {"valid","v1","v2","dx","dy","angle","flags","special","tag","taglist","args","stringargs","sidenum","frontside","backside","alpha","executordelay","slopetype","frontsector","backsector","polyobj","text","callcount"}
F.side = {"valid","textureoffset","rowoffset","offsetx_top","offsety_top","offsetx_mid","offsety_mid","offsetx_bottom","offsetx_bot","offsety_bottom","offsety_bot","scalex_top","scaley_top","scalex_mid","scaley_mid","scalex_bottom","scaley_bottom","toptexture","bottomtexture","midtexture","line","sector","special","repeatcnt","light","light_top","light_mid","light_bottom","lightabsolute","lightabsolute_top","lightabsolute_mid","lightabsolute_bottom","text"}
F.vertex = {"valid","x","y","floorz","floorzset","ceilingz","ceilingzset"}
F.ffloor = {"valid","topheight","toppic","toplightlevel","topxoffs","topyoffs","topxscale","topyscale","bottomheight","bottompic","bottomxoffs","bottomyoffs","bottomxscale","bottomyscale","t_slope","b_slope","sector","fofflags","flags","master","target","next","prev","alpha","blend","bustflags","busttype","busttag","sinkspeed","friction","bouncestrength"}
F.seg = {"valid","v1","v2","side","offset","angle","sidedef","linedef","frontsector","backsector","polyseg"}
F.node = {"valid","x","y","dx","dy","bbox","children"}
F.slope = {"valid","o","d","zdelta","normal","zangle","xydirection","flags"}
F.mapheader = {"lvlttl","subttl","actnum","typeoflevel","nextlevel","marathonnext","keywords","musname","mustrack","muspos","musinterfadeout","musintername","muspostbossname","muspostbosstrack","muspostbosspos","muspostbossfadein","musforcereset","forcecharacter","weather","skynum","skybox_scalex","skybox_scaley","skybox_scalez","precutscenenum","cutscenenum","countdown","palette","numlaps","unlockrequired","levelselect","bonustype","ltzzpatch","ltzztext","ltactdiamond","maxbonuslives","levelflags","menuflags","selectheading","startrings","sstimer","ssspheres","gravity"}
F.mobj = {"valid","x","y","z","snext","sprev","angle","pitch","roll","spriteroll","rollangle","sprite","frame","sprite2","anim_duration","spritexscale","spriteyscale","spritexoffset","spriteyoffset","floorspriteslope","drawonlyforplayer","dontdrawforviewmobj","touching_sectorlist","subsector","floorz","ceilingz","floorrover","ceilingrover","radius","height","momx","momy","momz","pmomz","tics","state","flags","flags2","eflags","renderflags","skin","color","translation","blendmode","alpha","bnext","bprev","hnext","hprev","type","info","health","movedir","movecount","target","reactiontime","threshold","player","lastlook","spawnpoint","tracer","friction","movefactor","fuse","watertop","waterbottom","mobjnum","scale","destscale","scalespeed","extravalue1","extravalue2","cusval","cvmem","standingslope","colorized","mirrored","shadowscale","dispoffset"}
F.mapthing = {"valid","x","y","angle","pitch","roll","type","options","scale","spritexscale","spriteyscale","z","extrainfo","tag","taglist","args","stringargs","mobj"}
F.player = {"valid","name","realmo","mo","cmd","playerstate","camerascale","shieldscale","viewz","viewheight","deltaviewheight","bob","viewrollangle","aiming","drawangle","rings","spheres","pity","currentweapon","ringweapons","ammoremoval","ammoremovaltimer","ammoremovalweapon","powers","pflags","panim","flashcount","flashpal","skincolor","skin","availabilities","score","recordscore","dashspeed","normalspeed","runspeed","thrustfactor","accelstart","acceleration","charability","charability2","charflags","thokitem","spinitem","revitem","followitem","followmobj","actionspd","mindash","maxdash","jumpfactor","height","spinheight","lives","continues","xtralife","gotcontinue","speed","secondjump","fly1","scoreadd","glidetime","climbing","deadtimer","exiting","homing","dashmode","skidtime","cmomx","cmomy","rmomx","rmomy","numboxes","totalring","realtime","laps","ctfteam","gotflag","weapondelay","tossdelay","starpostx","starposty","starpostz","starpostnum","starposttime","starpostangle","starpostscale","angle_pos","old_angle_pos","axis1","axis2","bumpertime","flyangle","drilltimer","linkcount","linktimer","anotherflyangle","nightstime","drillmeter","drilldelay","bonustime","capsule","drone","oldscale","mare","marelap","marebonuslap","marebegunat","lastmaretime","startedtime","finishedtime","lapbegunat","lapstartedtime","finishedspheres","finishedrings","marescore","lastmarescore","totalmarescore","lastmare","lastmarelap","lastmarebonuslap","totalmarelap","totalmarebonuslap","maxlink","texttimer","textvar","lastsidehit","lastlinehit","losstime","timeshit","onconveyor","awayviewmobj","awayviewtics","awayviewaiming","spectator","outofcoop","bot","botleader","lastbuttons","blocked","jointime","quittime","lastinputtime","ping","fovadd"}
F.ticcmd = {"forwardmove","sidemove","angleturn","aiming","buttons","latency"}
F.skin = {"valid","name","wadnum","flags","realname","hudname","supername","ability","ability2","thokitem","spinitem","revitem","followitem","actionspd","mindash","maxdash","normalspeed","runspeed","thrustfactor","accelstart","acceleration","jumpfactor","radius","height","spinheight","shieldscale","camerascale","starttranscolor","prefcolor","supercolor","prefoppositecolor","highresscale","contspeed","contangle","soundsid","sprites","skinsprites","supersprites","natkcolor"}
F.polyobj = {"valid","id","parent","vertices","lines","sector","angle","damage","thrust","flags","translucency","triggertag","pointInside","mobjTouching","mobjInside","moveXY","rotate"}
F.mobjinfo = {"doomednum","spawnstate","spawnhealth","seestate","seesound","reactiontime","attacksound","painstate","painchance","painsound","meleestate","missilestate","deathstate","xdeathstate","deathsound","speed","radius","height","dispoffset","mass","damage","activesound","flags","raisestate"}
F.sfxinfo = {"name","singular","priority","flags","caption","skinsound"}
F.extracolormap = {"red","green","blue","alpha","color","fade_red","fade_green","fade_blue","fade_alpha","fade_color","fade_start","fade_end"}

local function P(...)
	local t = {...}
	local s = {}
	for i = 1, select("#", ...) do s[#s+1] = tostring(t[i]) end
	print("LQ " .. table.concat(s, " "))
end
-- indexes of the engine structures, so that a reference to a sector / line / side / vertex prints as its number (pointers differ)
local idx = {sector = {}, line = {}, side = {}, vertex = {}, subsector = {}, seg = {}, node = {}}
local HAVE_SEGS = pcall(function() return segs[0] end)
local function build()
	for i = 0, #sectors - 1 do idx.sector[sectors[i]] = i end
	for i = 0, #lines - 1 do idx.line[lines[i]] = i end
	for i = 0, #sides - 1 do idx.side[sides[i]] = i end
	for i = 0, #vertexes - 1 do idx.vertex[vertexes[i]] = i end
	for i = 0, #subsectors - 1 do idx.subsector[subsectors[i]] = i end
	if HAVE_SEGS then
		for i = 0, #segs - 1 do idx.seg[segs[i]] = i end
		for i = 0, #nodes - 1 do idx.node[nodes[i]] = i end
	end
end
local function fmt(v, depth)
	local t = type(v)
	if t == "number" or t == "boolean" or t == "nil" then return tostring(v) end
	if t == "string" then return '"' .. v .. '"' end
	if t == "userdata" then
		for _, kind in ipairs({"sector", "line", "side", "vertex", "subsector", "seg", "node"}) do
			local i = idx[kind][v]
			if i then return kind .. "#" .. i end
		end
		if depth and depth > 0 then
			local ok, ty = pcall(function() return v.type end)
			local ok2, x = pcall(function() return v.x end)
			if ok and ok2 and type(ty) == "number" and type(x) == "number" then return "mo(" .. ty .. "," .. (x >> 16) .. ")" end
		end
		return "userdata"
	end
	if t == "table" then
		local keys = {}
		for k in pairs(v) do keys[#keys+1] = tostring(k) end
		table.sort(keys)
		return "table[" .. #keys .. "]"
	end
	return t
end
local function dump(kind, obj, tag)
	local out = {}
	for _, f in ipairs(F[kind]) do
		local ok, v = pcall(function() return obj[f] end)
		if ok then out[#out+1] = f .. "=" .. fmt(v, 1) else out[#out+1] = f .. "=E:" .. (tostring(v):gsub("^.-:%d+: ", "")) end
	end
	P(kind, tag, table.concat(out, " "))
end
local function digest(kind, list, n)
	local h = 17
	for i = 0, n - 1 do
		local obj = list(i)
		if obj then
			for _, f in ipairs(F[kind]) do
				local ok, v = pcall(function() return obj[f] end)
				local s = ok and fmt(v) or "E"
				for c = 1, #s do h = (h * 31 + s:byte(c)) % 1000003 end
			end
		end
	end
	return h
end
local done = false
addHook("ThinkFrame", function()
	if done or leveltime ~= 20 then return end
	done = true
	build()
	P("counts", #sectors, #lines, #sides, #vertexes, #subsectors, HAVE_SEGS)
	P("digest_all", "sector", digest("sector", function(i) return sectors[i] end, #sectors), "line", digest("line", function(i) return lines[i] end, #lines),
		"side", digest("side", function(i) return sides[i] end, #sides), "vertex", digest("vertex", function(i) return vertexes[i] end, #vertexes),
		"subsector", digest("subsector", function(i) return subsectors[i] end, #subsectors))
	if HAVE_SEGS then P("digest_segs", digest("seg", function(i) return segs[i] end, #segs), digest("node", function(i) return nodes[i] end, #nodes)) end
	for i = 0, min(#sectors, 40) - 1 do dump("sector", sectors[i], i) end
	for i = 0, min(#lines, 60) - 1 do dump("line", lines[i], i) end
	for i = 0, min(#sides, 60) - 1 do dump("side", sides[i], i) end
	for i = 0, min(#vertexes, 30) - 1 do dump("vertex", vertexes[i], i) end
	for i = 0, min(#subsectors, 30) - 1 do dump("subsector", subsectors[i], i) end
	if HAVE_SEGS then
		for i = 0, min(#segs, 40) - 1 do dump("seg", segs[i], i) end
		for i = 0, min(#nodes, 30) - 1 do dump("node", nodes[i], i) end
	end
	local function try(sec, f) local ok, e = pcall(f) if not ok then P("section_err", sec, (tostring(e):gsub("^.-:%d+: ", ""))) end end
	try("slopes", function() local n = 0 for sl in slopes.iterate do n = n + 1 if n <= 5 then dump("slope", sl, n) end end P("slopes", n) end)
	try("polyobjs", function() local n = 0 for po in polyobjects.iterate do n = n + 1 if n <= 3 then dump("polyobj", po, n) end end P("polyobjs", n) end)
	local k = 0
	for mo in mobjs.iterate() do
		k = k + 1
		if k <= 120 then dump("mobj", mo, k) end
	end
	P("mobjcount", k)
	for i = 0, 3 do if players[i] then dump("player", players[i], i) if players[i].cmd then dump("ticcmd", players[i].cmd, i) end end end
	for i = 0, 7 do local ok, sk = pcall(function() return skins[i] end) if ok and sk then dump("skin", sk, i) end end
	local ok, mh = pcall(function() return mapheaderinfo[gamemap] end) if ok and mh then dump("mapheader", mh, gamemap) end
	for _, t in ipairs({MT_PLAYER, MT_BLUECRAWLA, MT_RING, MT_THOK, MT_YELLOWSPRING, MT_GFZFLOWER1}) do dump("mobjinfo", mobjinfo[t], t) end
	for _, t in ipairs({sfx_jump, sfx_thok, sfx_pop}) do dump("sfxinfo", sfxinfo[t], t) end
	for i = 0, min(#sectors, 40) - 1 do
		local s = sectors[i]
		local ok, ex = pcall(function() return s.extra_colormap end)
		if ok and ex then dump("extracolormap", ex, i) end
		local ok2, ff = pcall(function() return s.ffloors end)
		if ok2 and ff then local c = 0 for f in ff() do c = c + 1 if c <= 3 then dump("ffloor", f, i .. "/" .. c) end end if c > 0 then P("ffloors", i, c) end end
	end
	try("mapthings", function() local mt = 0 for i = 0, #mapthings - 1 do mt = mt + 1 if i < 40 then dump("mapthing", mapthings[i], i) end end P("mapthings", mt) end)
	P("DONE_FIELDS")
end)

