-- GENERATED by gen_fields.py from the *_opt[] tables of src/lua_*.c: do not edit
local F = {}
F.sector = {"valid","floorheight","ceilingheight","floorpic","floorxoffset","flooryoffset","floorxscale","flooryscale","floorangle","ceilingpic","ceilingxoffset","ceilingyoffset","ceilingxscale","ceilingyscale","ceilingangle","lightlevel","floorlightlevel","floorlightabsolute","floorlightsec","ceilinglightlevel","ceilinglightabsolute","ceilinglightsec","special","tag","taglist","thinglist","heightsec","camsec","lines","ffloors","f_slope","c_slope","colormap","flags","specialflags","damagetype","triggertag","triggerer","friction","gravity"}
F.subsector = {"valid","sector","numlines","firstline","polyList"}
F.line = {"valid","v1","v2","dx","dy","angle","flags","special","tag","taglist","args","stringargs","sidenum","frontside","backside","alpha","executordelay","slopetype","frontsector","backsector","polyobj","text","callcount"}
F.side = {"valid","textureoffset","rowoffset","offsetx_top","offsety_top","offsetx_mid","offsety_mid","offsetx_bottom","offsetx_bot","offsety_bottom","offsety_bot","scalex_top","scaley_top","scalex_mid","scaley_mid","scalex_bottom","scaley_bottom","toptexture","bottomtexture","midtexture","line","sector","special","repeatcnt","light","light_top","light_mid","light_bottom","lightabsolute","lightabsolute_top","lightabsolute_mid","lightabsolute_bottom","text"}
F.vertex = {"valid","x","y","floorz","floorzset","ceilingz","ceilingzset"}
F.ffloor = {"valid","topheight","toppic","toplightlevel","topxoffs","topyoffs","topxscale","topyscale","bottomheight","bottompic","bottomxoffs","bottomyoffs","bottomxscale","bottomyscale","t_slope","b_slope","sector","fofflags","flags","master","target","next","prev","alpha","blend","bustflags","busttype","busttag","sinkspeed","friction","bouncestrength"}
F.seg = {"valid","v1","v2","side","offset","angle","sidedef","linedef","frontsector","backsector","polyseg"}
F.node = {"valid","x","y","dx","dy","bbox","children"}
F.slope = {"valid","o","d","zdelta","normal","zangle","xydirection","flags"}
F.mapheader = {"lvlttl","subttl","actnum","typeoflevel","nextlevel","marathonnext","keywords","musname","mustrack","muspos","musinterfadeout","musintername","muspostbossname","muspostbosstrack","muspostbosspos","muspostbossfadein","musforcereset","forcecharacter","weather","skynum","skybox_scalex","skybox_scaley","skybox_scalez","precutscenenum","cutscenenum","countdown","palette","numlaps","unlockrequired","levelselect","bonustype","ltzzpatch","ltzztext","ltactdiamond","maxbonuslives","levelflags","menuflags","selectheading","startrings","sstimer","ssspheres","gravity"}
F.mobj = {"valid","x","y","z","snext","sprev","angle","pitch","roll","spriteroll","rollangle","sprite","frame","sprite2","anim_duration","spritexscale","spriteyscale","spritexoffset","spriteyoffset","floorspriteslope","drawonlyforplayer","dontdrawforviewmobj","touching_sectorlist","subsector","floorz","ceilingz","floorrover","ceilingrover","radius","height","momx","momy","momz","pmomz","tics","state","flags","flags2","eflags","renderflags","skin","color","translation","blendmode","alpha","bnext","bprev","hnext","hprev","type","info","health","movedir","movecount","target","reactiontime","threshold","player","lastlook","spawnpoint","tracer","friction","movefactor","fuse","watertop","waterbottom","mobjnum","scale","destscale","scalespeed","extravalue1","extravalue2","cusval","cvmem","standingslope","colorized","mirrored","shadowscale","dispoffset"}
F.mapthing = {"valid","x","y","angle","pitch","roll","type","options","scale","spritexscale","spriteyscale","z","extrainfo","tag","taglist","args","stringargs","mobj"}
F.player = {"valid","name","realmo","mo","cmd","playerstate","camerascale","shieldscale","viewz","viewheight","deltaviewheight","bob","viewrollangle","aiming","drawangle","rings","spheres","pity","currentweapon","ringweapons","ammoremoval","ammoremovaltimer","ammoremovalweapon","powers","pflags","panim","flashcount","flashpal","skincolor","skin","availabilities","score","recordscore","dashspeed","normalspeed","runspeed","thrustfactor","accelstart","acceleration","charability","charability2","charflags","thokitem","spinitem","revitem","followitem","followmobj","actionspd","mindash","maxdash","jumpfactor","height","spinheight","lives","continues","xtralife","gotcontinue","speed","secondjump","fly1","scoreadd","glidetime","climbing","deadtimer","exiting","homing","dashmode","skidtime","cmomx","cmomy","rmomx","rmomy","numboxes","totalring","realtime","laps","ctfteam","gotflag","weapondelay","tossdelay","starpostx","starposty","starpostz","starpostnum","starposttime","starpostangle","starpostscale","angle_pos","old_angle_pos","axis1","axis2","bumpertime","flyangle","drilltimer","linkcount","linktimer","anotherflyangle","nightstime","drillmeter","drilldelay","bonustime","capsule","drone","oldscale","mare","marelap","marebonuslap","marebegunat","lastmaretime","startedtime","finishedtime","lapbegunat","lapstartedtime","finishedspheres","finishedrings","marescore","lastmarescore","totalmarescore","lastmare","lastmarelap","lastmarebonuslap","totalmarelap","totalmarebonuslap","maxlink","texttimer","textvar","lastsidehit","lastlinehit","losstime","timeshit","onconveyor","awayviewmobj","awayviewtics","awayviewaiming","spectator","outofcoop","bot","botleader","lastbuttons","blocked","jointime","quittime","lastinputtime","ping","fovadd"}
F.ticcmd = {"forwardmove","sidemove","angleturn","aiming","buttons","latency"}
F.skin = {"valid","name","wadnum","flags","realname","hudname","supername","ability","ability2","thokitem","spinitem","revitem","followitem","actionspd","mindash","maxdash","normalspeed","runspeed","thrustfactor","accelstart","acceleration","jumpfactor","radius","height","spinheight","shieldscale","camerascale","starttranscolor","prefcolor","supercolor","prefoppositecolor","highresscale","contspeed","contangle","soundsid","sprites","skinsprites","supersprites","natkcolor"}
F.polyobj = {"valid","id","parent","vertices","lines","angle","damage","thrust","flags","translucency","triggertag","pointInside","mobjTouching","mobjInside","moveXY","rotate"}
F.mobjinfo = {"doomednum","spawnstate","spawnhealth","seestate","seesound","reactiontime","attacksound","painstate","painchance","painsound","meleestate","missilestate","deathstate","xdeathstate","deathsound","speed","radius","height","dispoffset","mass","damage","activesound","flags","raisestate"}
F.sfxinfo = {"name","singular","priority","flags","caption","skinsound"}
F.extracolormap = {"red","green","blue","alpha","color","fade_red","fade_green","fade_blue","fade_alpha","fade_color","fade_start","fade_end"}


local function P(...)
	local t = {...}
	local s = {}
	for i = 1, select("#", ...) do s[#s+1] = tostring(t[i]) end
	print("LQ " .. table.concat(s, " "))
end
-- OPT14 (lt_maps): the digest of lt_fields over many maps in one run. Each map: at leveltime 4 every field of every sector, line, side, vertex, subsector, seg, node, ffloor, slope, polyobject, mapthing
-- and mobj is read through Lua and hashed (references print as indexes); then the next map of the list is loaded (map NN -force). The list comes from the first lines of the game: "{1,2,3,4,5,6,7,8,9,10,11}" below.
local MAPS = {1,2}
local idx = {sector = {}, line = {}, side = {}, vertex = {}, subsector = {}, seg = {}, node = {}, slope = {}, ffloor = {}, polyobj = {}, mapthing = {}}
local HAVE_SEGS = pcall(function() return segs[0] end)
-- (OPT14) a map with more than LIGHTMAX lines + sides + vertexes keeps no index of them (68 000 userdata with their index tables take 8 MB of Lua heap, which the PS2 does not have next to the level):
-- a reference to a line, side, vertex, subsector, seg or node is then written as a fingerprint of the object (its coordinates, textures, sector index); the sectors, FOFs, slopes, polyobjects
-- and map things are still indexed.
local LIGHTMAX = 20000
local light = false
local function build()
	for k in pairs(idx) do idx[k] = {} end
	light = (#lines + #sides + #vertexes) > LIGHTMAX
	for i = 0, #sectors - 1 do idx.sector[sectors[i]] = i end
	if not light then
		for i = 0, #lines - 1 do idx.line[lines[i]] = i end
		for i = 0, #sides - 1 do idx.side[sides[i]] = i end
		for i = 0, #vertexes - 1 do idx.vertex[vertexes[i]] = i end
		for i = 0, #subsectors - 1 do idx.subsector[subsectors[i]] = i end
		if HAVE_SEGS then
			for i = 0, #segs - 1 do idx.seg[segs[i]] = i end
			for i = 0, #nodes - 1 do idx.node[nodes[i]] = i end
		end
	end
	local n = 0
	pcall(function() for sl in slopes.iterate do idx.slope[sl] = n n = n + 1 end end)
	n = 0
	pcall(function() for po in polyobjects.iterate do idx.polyobj[po] = n n = n + 1 end end)
	pcall(function() for i = 0, #mapthings - 1 do idx.mapthing[mapthings[i]] = i end end)
	n = 0
	for i = 0, #sectors - 1 do
		local ok, ff = pcall(function() return sectors[i].ffloors end)
		if ok and ff then for f in ff() do idx.ffloor[f] = n n = n + 1 end end
	end
end
local KINDS = {"sector", "line", "side", "vertex", "subsector", "seg", "node", "slope", "ffloor", "polyobj", "mapthing"}
local fmt
function fmt(v, inner, fname)
	local t = type(v)
	if t == "number" or t == "boolean" or t == "nil" then return tostring(v) end
	if t == "string" then return '"' .. v .. '"' end
	if t == "userdata" then
		for _, kind in ipairs(KINDS) do
			local i = idx[kind][v]
			if i then return kind .. "#" .. i end
		end
		local ok, ty = pcall(function() return v.type end)
		local ok2, x = pcall(function() return v.x end)
		if ok and ok2 and type(ty) == "number" and type(x) == "number" then return "mo(" .. ty .. "," .. (x >> 16) .. ")" end
		if light then
			local function try(f) local ok, r = pcall(f) if ok then return r end end
			local function px(vx) return vx and (vx.x >> 16) .. "," .. (vx.y >> 16) or "?" end
			local v1, v2 = try(function() return v.v1 end), try(function() return v.v2 end)
			if v1 and v2 then
				if try(function() return v.dx end) then return "line(" .. px(v1) .. "," .. px(v2) .. ")" end
				local sd = try(function() return v.side end)
				if sd then return "seg(" .. px(v1) .. "," .. px(v2) .. "," .. sd .. ")" end
			end
			local top = try(function() return v.toptexture end)
			if top then
				local sec = try(function() return v.sector end)
				return "side(" .. top .. "," .. v.midtexture .. "," .. v.bottomtexture .. "," .. (v.textureoffset >> 16) .. "," .. (v.rowoffset >> 16) .. "," .. tostring(sec and idx.sector[sec]) .. ")"
			end
			if try(function() return v.floorzset end) ~= nil then return "vertex(" .. px(v) .. ")" end
			local nl = try(function() return v.numlines end)
			if nl then return "subsector(" .. tostring(idx.sector[v.sector]) .. "," .. nl .. ")" end
			local bb = try(function() return v.bbox end)
			if bb then return "node(" .. (v.x >> 16) .. "," .. (v.y >> 16) .. "," .. (v.dx >> 16) .. "," .. (v.dy >> 16) .. ")" end
		end
		-- (OPT14) a list userdata (line.args, line.stringargs, mapthing.args, taglist, sector.lines, ...): its length and its elements, the PS2 keeps line.args in a block of its own
		if not inner then
			local okn, n = pcall(function() return #v end)
			if okn and type(n) == "number" and n >= 0 and n <= 64 then
				local parts = {}
				for i = (fname == "taglist" and 1 or 0), (fname == "taglist" and n or n - 1) do -- (tag lists count from 1: [0] reads before the array)
					local oke, e = pcall(function() return v[i] end)
					parts[#parts + 1] = oke and fmt(e, true) or "E"
				end
				return "[" .. n .. ":" .. table.concat(parts, ",") .. "]"
			end
		end
		return "userdata"
	end
	if t == "table" then return "table" end
	return t
end
local function mix(h, s)
	for c = 1, #s do h = (h * 31 + s:byte(c)) % 1000003 end
	return h
end
local function digest(kind, iter)
	local h, n = 17, 0
	local fh, ex = {}, {}
	local badn
	for obj in iter do
		n = n + 1
		for _, f in ipairs(F[kind]) do
			local ok, v = pcall(function() return obj[f] end)
			local str = ok and fmt(v, false, f) or "E"
			h = mix(h, str)
			if f == "valid" and str ~= "true" then badn = (badn or 0) + 1 if badn <= 8 then P("bad", kind, n - 1, str, tostring(ok), tostring(v)) end end
			fh[f] = mix(fh[f] or 17, str)
			if (kind == "line" or kind == "subsector") and (f == "args" or f == "stringargs" or f == "taglist" or f == "polyobj" or f == "polyList" or f == "firstline" or f == "slopetype" or f == "callcount") and str ~= "nil" and str ~= "false" and #ex < 400 then ex[#ex + 1] = f .. " " .. (n - 1) .. " " .. str end
		end
	end
	P("badcount", kind, badn or 0)
	if kind == "line" or kind == "subsector" then
		for _, f in ipairs(F[kind]) do P("fld", kind, f, fh[f]) end
		for _, e in ipairs(ex) do P("ex", kind, e) end
	end
	return h, n
end
local function range(list, n)
	local i = -1
	return function() i = i + 1 if i < n then return list[i] end end
end
local function ffloors_iter()
	local fl = {}
	for i = 0, #sectors - 1 do
		local ok, ff = pcall(function() return sectors[i].ffloors end)
		if ok and ff then for f in ff() do fl[#fl + 1] = f end end
	end
	local i = 0
	return function() i = i + 1 return fl[i] end
end
local function mobj_iter()
	local fl = {}
	for mo in mobjs.iterate() do fl[#fl + 1] = mo end
	local i = 0
	return function() i = i + 1 return fl[i] end
end
local mi, state, started = 1, 0, false
local function chk(tag) local ok, a = pcall(function() return lines[1676].valid end) local ok2, b = pcall(function() return lines[1732].valid end) P("chk", tag, tostring(a), tostring(b), #lines) end
local function report(m)
	print("LP luakb start " .. m .. " " .. collectgarbage("count"))
	chk("start")
	build()
	chk("built")
	local parts = {}
	local function add(kind, h, n) parts[#parts + 1] = kind .. "=" .. n .. "/" .. h end
	local h, n
	h, n = digest("sector", range(sectors, #sectors)) add("sector", h, n) chk("after sectors")
	h, n = digest("line", range(lines, #lines)) add("line", h, n)
	h, n = digest("side", range(sides, #sides)) add("side", h, n)
	h, n = digest("vertex", range(vertexes, #vertexes)) add("vertex", h, n)
	h, n = digest("subsector", range(subsectors, #subsectors)) add("subsector", h, n)
	if HAVE_SEGS then
		h, n = digest("seg", range(segs, #segs)) add("seg", h, n)
		h, n = digest("node", range(nodes, #nodes)) add("node", h, n)
	end
	h, n = digest("ffloor", ffloors_iter()) add("ffloor", h, n)
	pcall(function() h, n = digest("slope", slopes.iterate) add("slope", h, n) end)
	pcall(function() h, n = digest("polyobj", polyobjects.iterate) add("polyobj", h, n) end)
	pcall(function() h, n = digest("mapthing", range(mapthings, #mapthings)) add("mapthing", h, n) end)
	h, n = digest("mobj", mobj_iter()) add("mobj", h, n)
	local mh = "-"
	pcall(function() local hh = 17 for _, f in ipairs(F.mapheader) do local ok, v = pcall(function() return mapheaderinfo[gamemap][f] end) hh = mix(hh, ok and fmt(v) or "E") end mh = hh end)
	P("map", m, "mapheader", mh, table.concat(parts, " "))
	print("LP luakb end " .. m .. " " .. collectgarbage("count"))
end
addHook("ThinkFrame", function()
	if mi > #MAPS then return end
	if state == 0 and leveltime == 4 and gamemap == MAPS[mi] then
		state = 1
		report(MAPS[mi])
		mi = mi + 1
		if mi > #MAPS then P("DONE_MAPS") return end
		COM_BufInsertText(server, "map " .. MAPS[mi] .. " -force")
		state = 0
	end
end)
P("registered", #MAPS)
